name: advantech-imx6-gadget
version: 1.0
summary: Advantech i.Mx6 gadget snap
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core 18 image for the Advantech i.mx6 platform.
type: gadget
base: core18
architectures:
  - build-on: [armhf]
    run-on: armhf
confinement: strict
grade: stable

parts:
  uboot:
    plugin: nil
    source: https://github.com/ADVANTECH-Corp/uboot-imx6.git
    source-branch: imx_v2018.03_4.14.98_2.0.0_ga
    override-build: |
      make mx6dlsabresd_defconfig
      if [ "$(arch)" = "x86_64" ]; then
        CROSS_COMPILE=arm-linux-gnueabihf- make
      else
        make
      fi
      mkdir -p $SNAPCRAFT_PART_INSTALL/boot-assets
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      ln -s uboot.env $SNAPCRAFT_PART_INSTALL/uboot.conf
    build-packages:
      - libpython2.7-dev
      - build-essential
      - bc
      - wget
      - cpio
      - findutils
      - xz-utils
      - html2text
      - bison
      - flex
